project.version=6.2.0+26.1
project.java=25
project.build-java=25
project.minecraft=26.1
project.enabled-loaders=fabric,forge,neoforge

mod.minecraft-range=[26.1, 27)
mod.fabric-range=>=26.1
mod.forge-loader-range=[62,)
mod.neoforge-loader-range=[4,)

publish.game-versions=26.1
dependencies.curios=15.0.0+26.1.2
dependencies.trinkets=4.0.0-rc.1+26.1
dependencies.trinkets-neoforge=4.0.0-alpha.9+26.1
