name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: iamkaf/multiloader-conventions/.github/workflows/mod-build.yml@1e7007e0ce3a8a7ec41adb02f65a78a6baabda8a

    with:
      teakit-runner: gradle
      teakit-loaders: fabric,forge,neoforge
